version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    networks:
      - test
    volumes:
      - db:/var/lib/mysql
  gestionstationski:
    depends_on:
      - mysqldb
    image: khaznaji/oumaymalynakhaznaji-5sae4-g1-gestion-station-ski:latest
    ports:
      - "8089:8089"
    networks:
      - test
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : null

          }'
      stdin_open: true
      tty: true
networks:
  test:
    driver: bridge
volumes:
  db:
